sudo: required
services:
  - docker

before_install:
  - docker build -t tifla/learn-docker -f Dockerfile.dev .

script:
  docker run tifla/learn-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-794884163200"
  bucket_path: "docker-react"
  on:
   branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"